### ISSUE TITLE
Deep comparison using MemberwiseEqualityComparer<T>

### ISSUE THREAD

**Issue by nzbart** [thedmi/Equ#2]
I am trying to compare complex POCOs using `MemberwiseEqualityComparer<T>`, but found that some comparisons are not working as I originally expected. Should nested classes / objects be compared? 

The following test illustrates what I am trying to do:

```csharp
using Equ;
using NUnit.Framework;

[TestFixture]
class Tests
{
    private class NestedType
    {
        public string InnerValue { get; set; }
    }

    class ValueTypeWithCustomProperty
    {
        public NestedType Value { get; set; }
    }

    [Test]
    public void Properties_are_compared_recursively_even_without_MemberwiseEquatable_base_class()
    {
        var value1 = new ValueTypeWithCustomProperty { Value = new NestedType { InnerValue = "test" } };
        var value2 = new ValueTypeWithCustomProperty { Value = new NestedType { InnerValue = "test" } };

        var comparer = MemberwiseEqualityComparer<ValueTypeWithCustomProperty>.ByProperties;
        var result = comparer.Equals(value1, value2);

        Assert.That(result, Is.True);
    }
}
```

**Comment by thedmi** [comment]
This is the expected behavior, because `NestedType` is not a value type. `Equ` calls  `Equals()` on nested reference-typed objects, and because you're creating two `NestedType` instances, they are not considered equal. This behavior is consistent with *entities*, as defined by domain-driven design.

To get the behavior that you want, you need to make sure that all nested types that you want to compare by value provide an `Equals()` method that does so. The easiest way to achieve this is by inheriting `NestedType` from `MemberwiseEquatable<NestedType>`. Or, if you don't want to derive from a base class, you can override the `Equals()` method yourself and use a `MemberwiseEqualityComparer<NestedType>` there.

See also the [Value_objects_with_equal_members_are_equal](https://github.com/thedmi/Equ/blob/master/Sources/EquTest/MemberwiseEquatableTest.cs#L30) test in the sources for an example of your case.

**Comment by nzbart** [comment]
Would you consider extending your library to support this scenario (e.g. via a `.ByPropertiesDeep` or similar extension), or does that not fit in with the basic philosophy of what you're trying to achieve here?

What I'm after is a high performance comparison library - which your library mostly achieves. Would you have any objections to me forking this project if a deep comparison doesn't fit your project? I notice that it is licensed under MIT, but thought it would be polite to ask anyway...

**Comment by thedmi** [comment]
Since Equ is designed to support domain-driven design projects, I don't think that such an extension would be a step in the right direction, because that would blindly treat every object as value object. I see your case, it's just something Equ is not designed for.

Go ahead, of course you can for it! You'll be mostly interested in the equality function generation part of Equ, which can be found in [EqualityFunctionGenerator.cs](https://github.com/thedmi/Equ/blob/master/Sources/Equ/EqualityFunctionGenerator.cs). I'll have to warn you though, the .NET expression tree stuff is a bit tricky at the beginning :-) . Don't hesitate to ask if you have any questions regarding my implementation.
